# Generated by Django 3.1.7 on 2021-03-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210326_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
