# Generated by Django 3.1.7 on 2021-03-26 14:43

import api.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210326_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='duration',
            field=models.PositiveIntegerField(validators=[api.validators.duration_validator]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.PositiveIntegerField(validators=[api.validators.duration_validator]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[api.validators.datetime_validator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(validators=[api.validators.duration_validator]),
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[api.validators.datetime_validator]),
        ),
    ]
